config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :users
  resources :courses

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

app/models/course.rb
class Course < ActiveRecord::Base

  validates :title, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base

  validates :password, :about, presence: true
  validates :user_name, presence: true, uniqueness: true

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

end

def current_user
  User.find_by(id: session[:user_id])
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]


  def index
    @courses = Course.all
  end

  def show
  end

  def new
    @course = Course.new
  end

  def edit
  end

  def create
    @course = Course.new(course_params)

    if @course.save
      redirect_to courses_path, notice: 'Course was successfully created.'
    else
      render :new
    end
  end

  def update
    if @course.update(course_params)
      redirect_to courses_path, notice: 'Course was successfully updated.'
    else
      render :edit
    end
  end


  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    redirect_to courses_path, notice: 'Course was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:title, :day_night)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(user_name: params[:user_name])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:alert] = "Invalid User Name and/or Password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]


  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_path, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to users_path, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end


  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:user_name, :about, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>

<% if @course.errors.any? %>
  <h2><%= pluralize(@course.errors.count, "error") %> prohibited this <%= @course.class %> from being saved:</h2>
  <ul>
  <% @course.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

<br/>

<%= f.label :title %>
<%= f.text_field :title %>

<br/>

<%= f.label :day_night, "Day?" %>
<%= f.check_box :day_night %> (Leave unchecked if a night course)

<br/>

<%= f.submit %>
<a href="/courses">Cancel</a>

<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<br/>

<%= render 'form' %>

app/views/courses/index.html.erb
<h1>Courses</h1>

<br/>

<%= link_to 'New Course', new_course_path %>

<br/><br/>

<table border=1>
  <thead>
    <tr>
      <th>Title</th>
      <th>Day or Night</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= link_to course.title, course %></td>
        <% if course.day_night == true %>
        <td>Day</td>
        <% else %>
        <td>Night</td>
        <% end %>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Delete', course_path(course), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/courses/new.html.erb
<h1>New Course</h1>

<br/>

<%= render 'form' %>

app/views/courses/show.html.erb
<h1><%= @course.title %></h1>

<br/>

<table border=1>
  <thead>
    <tr>
      <th>Title</th>
      <th>Day or Night</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @course.title %></td>
      <% if @course.day_night == true %>
      <td>Day</td>
      <% else %>
      <td>Night</td>
      <% end %>
    </tr>
  </tbody>
</table>

<br/>

<a href="/courses">Back</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JakeMarwilWeek7</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav>
    <ul>
      <% if current_user %>
        <li><%= link_to "#{current_user.user_name}", user_path(current_user) %></li>
        <li><%= link_to 'Log Out', logout_path %></li>
      <% else %>
        <li><%= link_to 'Log In', login_path %></li>
      <% end %>
    </ul>
  </nav>

<br/>

<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>

<br/>

<%= yield %>

<br/><br/>

<footer>
  <% if current_user %>
    <li><%= link_to 'Users', users_path %></li>
    <li><%= link_to 'Courses', courses_path %></li>
  <% end %>
</footer>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

<% if @user.errors.any? %>
  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.class %> from being saved:</h2>
  <ul>
  <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

<br/>

<%= f.label :user_name %>
<%= f.text_field :user_name %>

<br/>

<%= f.label :about %>
<%= f.text_field :about %>

<br/>

<%= f.label :password %>
<%= f.password_field :password %>

<br/>

<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>

<br/>

<%= f.submit %>
<a href="/users">Cancel</a>

<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<br/>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Users</h1>

<br/>

<%= link_to 'New User', new_user_path %>

<br/><br/>

<table border=1>
  <thead>
    <tr>
      <th>User Name</th>
      <th>About</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.user_name, user %></td>
        <td><%= user.about %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Delete', user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<br/>

<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.user_name %></h1>

<br/>

<table border=1>
  <thead>
    <tr>
      <th>User Name</th>
      <th>About</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @user.user_name %></td>
      <td><%= @user.about %></td>
    </tr>
  </tbody>
</table>

<br/>

<a href="/users">Back</a>

app/views/welcome/index.html.erb
<h1>Welcome!</h1>